POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@exemple.com"
}

###

GET  http://localhost:3333/invites/35f9bbaf-df62-48c5-9cc7-19b9846e015c